{
 "title": "Accounts",
 "time": { "from": "2024-11-20T01:42:42.204Z", "to": "2024-11-20T01:58:19.259Z" },
 "panels": [
  {
   "title": "Accounts Register",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(account_requested_counter_total)",
     "legendFormat": "Accounts Requested"
    },
    {
     "expr": "sum(account_created_counter_total)",
     "legendFormat": "Accounts Created"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transaction_handled_counter_total{ })",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(transaction_handled_counter_total{transaction_status=\"APPROVED\"})",
     "legendFormat": "Autorizadas"
    },
    {
     "expr": "sum(transaction_handled_counter_total{transaction_status=\"REJECTED\"})",
     "legendFormat": "Negadas"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_count[$__range]))\r\n",
     "legendFormat": "[{{method}}] {{uri}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, uri, status) (irate(http_server_requests_seconds_count[$__range]))\r\n",
     "legendFormat": "[{{method}}] {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(http_server_requests_seconds_sum[$__rate_interval])) / sum by (method, uri) (rate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "[{{method}}] - {{uri}}"
    }
   ]
  }
 ]
}