spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connectTimeout: 100
      timeout: 100
  kafka:
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      group-id: replace with your group id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # change this with your event packages
    producer:
      acks: -1
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

distributed-lock:
  type: redis
  timeout:
    lock: 15
  retry:
    count: 3
    sleep: 100

topics:
  transactions:
    name: transactions
  accounts:
    requests:
      name: accounts-request
    registers:
      name: accounts-registers