spring:
  data:
    redis:
      redisson:
        config: |
          singleServerConfig:
            idleConnectionTimeout: 1000
            connectTimeout: 1000
            timeout: 300
            retryAttempts: 3
            retryInterval: 100
            password: null
            subscriptionsPerConnection: 5
            clientName: null
            address: "redis://127.0.0.1:6379"
            subscriptionConnectionMinimumIdleSize: 1
            subscriptionConnectionPoolSize: 50
            connectionMinimumIdleSize: 24
            connectionPoolSize: 64
            database: 0
            dnsMonitoringInterval: 5000
          threads: 16
          nettyThreads: 32
          codec: !<org.redisson.codec.Kryo5Codec> {}
          transportMode: "NIO"
  kafka:
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      group-id: replace with your group id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # change this with your event packages
    producer:
      acks: -1
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer